# Generated by Django 4.2.5 on 2023-10-06 11:59

import accountapp.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', accountapp.manager.MyUserManager()),
            ],
        ),
    ]
