# Generated by Django 4.2.5 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_myuser_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
