# Generated by Django 4.2.6 on 2023-11-02 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterinstruction",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 2, 8, 19, 53, 157709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lettersummons",
            name="created_date_add",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 7, 8, 19, 53, 158500, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
