# Generated by Django 4.2.5 on 2023-10-22 11:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0002_alter_lettercourt_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('letter_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='letterinstruction',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 11, 55, 20, 257007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lettersummons',
            name='created_date_add',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 11, 55, 20, 257458, tzinfo=datetime.timezone.utc)),
        ),
    ]
